name: CI      

on: 
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go 1.22           
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Build 
      run: go build -o product-catalog-service src/product-catalog/main.go
    
    - name: Unit tests
      run: go test -v src/product-catalog/...
  
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run GolangCI-Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2
        golangci-lint run src/product-catalog/...
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
    - name: Install Docker   
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with: 
        context: src/product-catalog
        file: Dockerfile
        push: true  
        tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{github.run_id}}  

  updatek8s:
    runs-on: ubuntu-latest
    needs: docker
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        